"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://zh.moegirl.org.cn
  name = moegirl

Please do not commit this to the Git repository!
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'moegirl'
    langs = {
        'zh': 'zh.moegirl.org.cn',
        'en': 'en.moegirl.org.cn',
        'ja': 'ja.moegirl.org.cn',
        'commons': 'commons.moegirl.org.cn',
    }

    def scriptpath(self, code):
        return {
            'zh': '',
            'en': '',
            'ja': '',
            'commons': '',
        }[code]

    def protocol(self, code):
        return {
            'zh': 'https',
            'en': 'https',
            'ja': 'https',
            'commons': 'https',
        }[code]
